### ISSUE TITLE
Roadmap Arquitetura

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#110]
- [ ] Registrar os requisitos do ML-Produto

- [ ] Registrar o Roadmap da arquitetura de todo o projeto

- [ ] Registrar as principais dúvidas/gargalos na arquitetura

**Comment by victorcmoura** [comment]
Versão inicial do roadmap:
https://github.com/lappis-unb/salic-ml-web/blob/master/docs/roadmap_arquitetura.md

**Comment by victorcmoura** [comment]
Roadmap [disponível](https://github.com/lappis-unb/salic-ml-web/blob/master/docs/roadmap_arquitetura.md) e já foi colocado em formato de issues no [salic-ml-web](https://github.com/lappis-unb/salic-ml-web/issues)
