### ISSUE TITLE
Checklist de dúvidas sobre o banco de dados 

### ISSUE THREAD

**Issue by Mattioli** [lappis-unb/salic-ml#240]
Tirar as respectivas dúvidas (dadas como tarefas) com o time da SEFIC.

**Tarefas**
- [ ] **Atualizar lista de SQLs a serem validados**
- [x] Entender exatamente em qual fase um dado projeto está, com base em dados presentes no banco de dados;
- [x] Entender o porquê de alguns pronacs terem espaços em seus finais/começos;
- [ ] Validar a corretude das (nossas) queries .sql que são utilizadas no projeto atualmente;

**Critérios de aceitação**

- [x] Determinar em quais tabelas/colunas os dados referentes à fase de um dado projeto se encontram
- [ ] Queries .sql validadas e eventualmente issues de correção abertas

**Comment by marlonbymendes** [comment]
Para encontrar a fase de um projeto cultural:

```
SELECT * FROM sac.dbo.Verificacao WHERE idtipo = 26
```

Especificadamente para Análise Financeira:

```
651 - Fase de avaliação dos resultados da ação cultural
```

**Comment by marlonbymendes** [comment]
Sobre os caracteres especiais em PRONACs do banco:

> Só existe um pronac na base de dados com o nº XX-XXXX, só ocorreu mais ou memo em 1.996 para permitir a inabilitação de proponente que não tivessem projetos no MinC.

Ou seja, ainda não ficou claro o caso de PRONACS com espaços.

Falta também validar os `.sql` utilizado pelo ML.

**Comment by Duerno** [comment]
Documentando email trocado com o Rômulo a respeito dessas perguntas:

---
**Como identificar exatamente qual a fase de um projeto cultural?**
 
**Resposta:** A tabela  do  banco SAC tbProjetoFase identifica a fase do projeto.
 
O atributo é o idFase  e stEstado = 1
 
Na tabela Verificacao do banco SAC tem o significado de cada código do Fase
 
Para descobrir o significado basta rodar a query abaixo
 
SELECT * FROM sac.dbo.Verificacao WHERE idtipo = 26
 
 
**Precisamos identificar quais projetos já passaram pela fase "Análise de Resultados" e quais já estão aptos a passar por ela (tanto Análise de Objeto quanto Análise Financeira).**
 
**Resposta:** 651 - Fase de avaliação dos resultados da ação cultural
 
**Os scripts SQL que estamos utilizando estão disponíveis em nosso repositório (neste link) e gostaríamos que alguém do Ministério revisasse para termos garantia de estarmos utilizando os dados corretos**
 
**Resposta:** Não consegui acessar pelo link.
 
 
**Vimos que alguns PRONACs não são numéricos: alguns contêm "X" e outros têm espaços. Por que isso acontece? E é normal isso acontecer?**
 
**Resposta:** Só existe um pronac na base de dados com o nº XX-XXXX, só ocorreu mais ou memo em 1.996 para permitir a inabilitação de proponente que não tivessem projetos no MinC.

**Comment by marlonbymendes** [comment]
Ao final da sprint 5, falta validar as queries sql.

**Comment by victorcmoura** [comment]
Validações das queries ainda pendentes

**Comment by victorcmoura** [comment]
A issue [161](https://github.com/lappis-unb/salic-ml/issues/161) tem relação direta com a validação dos SQLs. Portanto ela será fechada e o seu conteúdo deve ser contemplado nesta issue.

**Comment by fabiolamfleury** [comment]
A issue #262 também está relacionada com a validação dos SQLs, nela estão descritas interpretações sobre as tabelas que devem ser validadas.
