### ISSUE TITLE
Reestruturação dos dados

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#293]
Otimização e padronização do data handling

- [x] Adicionar filtros para query por projeto
- [x] Cache
- [x] Documentação das fontes de dados
- [x] Automatização do download dos dados

**Comment by victorcmoura** [comment]
Em relação ao item "Documentação das fontes de dados", deve-se confirmar qual o critério de aceitação (A presença dos sql's no código é o suficiente? Deve existir um markdown indicando mais informações?)

**Comment by fabiolamfleury** [comment]
Existe essa página https://github.com/lappis-unb/salic-ml/wiki/Dados-sobre-finan%C3%A7as-dos-projetos-no-SALIC na wiki sobre os dados financeiros, vou editar ela para indicar onde estão os sql e como são utilizados

**Comment by victorcmoura** [comment]
Dado que os trabalhos foram finalizados, esta issue está sendo fechada.
