### ISSUE TITLE
Visualização das relações entre incentivadores, proponentes e fornecedores

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#294]
- [ ] Visualização do fluxo de recursos
- [x] Extrair informações dos CPFs/CNPJs (Nomes, municípios, tipo de pessoa, metadados...)
- [ ] Analisar informações relacionadas à geolocalização do(s) projeto/fornecedores
- [x] Verificar relações de sociedade
- [ ] Análise de nomes (parentesco, agregação de múltiplos CNPJs, ...)
- [ ] Relação inversa entre proponente (pessoa física) e fornecedor (empresa cujo proponente é sócio)
- [x] Incentivadores que foram contratados pelo proponente incentivado
- [ ] Alerta de incentivador único
- [ ] Alerta de incentivos únicos
- [ ] Alerta de recorrencias
  - [ ] Incentivos recorrentes ao mesmo proponente
  - [ ] Contratações recorrentes do mesmo fornecedor
- [ ] Identificação de consistência temporal (similaridade entre projetos?)

**Comment by victorcmoura** [comment]
A issue foi criada em um momento no qual não estávamos corretamente orientados sobre a análise de grafos/redes. Com a reunião realizada no dia 1º de abril, com Jackson, que nos orientou melhor sobre a parte técnica, esta issue não se faz necessária no contexto do projeto.
