### ISSUE TITLE
Junção dos repositórios (refatoração da estrutura técnica do projeto)

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#295]
- [x] Centralizar código no repositório salic-ml
- [ ] Criar pacote npm do frontend (Edit 11 mar 2019: Dockerizar o front)
- [x] Juntar APIs Lappis Learning e Salic-ml-web
- [x] Utilizar o django-boogie
- [ ] Análise da necessidade de escrita (tornar readonly)

**Comment by victorcmoura** [comment]
Em relação ao item "Análise da necessidade de escrita (tornar readonly)", deve-se definir quais operações devem ser readonly e o porquê.

Em relação ao item "Criar pacote npm do frontend", decidiu-se que a melhor abordagem seria dockerizar o front para disponibilizá-lo sem a necessidade do npm.

**Comment by victorcmoura** [comment]
Dado que a única issue pendente era dockerizar o front, e que esta demanda só se fará necessária no momento de dar deploy em produção, esta issue está sendo fechada por conta da conclusão das demais tarefas.
