### ISSUE TITLE
Pesquisa - Checklist de projetos de aprendizagem de máquina

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#30]
A partir das lições aprendidas, dos estudos, fazer a documentação/tutorial (não sei qual a melhor forma de apresentar o conteúdo) do pipeline de projetos de aprendizagem de máquina (mais didático e objetivo possível):

- [ ] Sugestão: Usar o Appendix B do livro como referência (pág 505) -> livro hands-on machine learning with scikit-learn and tensorflow;

- [ ]  Fazer uma primeira versão genérica

- [ ] Fazer uma versão adaptada para o salic ml (especifico dos dados do minc etc)

**Comment by Duerno** [comment]
Oi Carla, vou copiar sua mensagem na issue #29 e fechar esta, pois as duas tratam do mesmo assunto.
